### ISSUE TITLE
嗨，你好，服务器可以启动了，但是登录localhost：3000时又出现了新的错误

### ISSUE THREAD

**Issue by yangdonglai** [donniewang/koa-vue-example#3]
是的，更新之后服务器可以启动了，但是当我在浏览器中输入localhost：3000的时候，出现新的错误。
Koa server listening on 3000
ForbiddenError: Forbidden
at resolvePath (/Users/mac/Learn/koa-vue-example/node_modules/.1.3.3@resolve-path/index.js:82:11)
at /Users/mac/Learn/koa-vue-example/node_modules/.3.2.0@koa-send/index.js:68:12
at next (native)
at onFulfilled (/Users/mac/Learn/koa-vue-example/node_modules/.4.6.0@co/index.js:65:19)
at /Users/mac/Learn/koa-vue-example/node_modules/.4.6.0@co/index.js:54:5
at co (/Users/mac/Learn/koa-vue-example/node_modules/.4.6.0@co/index.js:50:10)
at send (/Users/mac/Learn/koa-vue-example/node_modules/.3.2.0@koa-send/index.js:36:10)
at Object.index$ (/Users/mac/Learn/koa-vue-example/app/server/index.js:71:15)
at tryCatch (/Users/mac/Learn/koa-vue-example/node_modules/.0.9.6@regenerator-runtime/runtime.js:63:40)
at GeneratorFunctionPrototype.invoke as _invoke
at GeneratorFunctionPrototype.prototype.(anonymous function) as next
at Object.dispatch (/Users/mac/Learn/koa-vue-example/node_modules/.5.4.0@koa-router/lib/router.js:336:14)
at next (native)
at onFulfilled (/Users/mac/Learn/koa-vue-example/node_modules/.4.6.0@co/index.js:65:19)
at /Users/mac/Learn/koa-vue-example/node_modules/.4.6.0@co/index.js:54:5
at Object.co (/Users/mac/Learn/koa-vue-example/node_modules/.4.6.0@co/index.js:50:10)
::1 [2016-11-17 09:53:28] GET / 500 19 ms

**Comment by donniewang** [comment]
这个项目是9个月前的，目前koa-send 这个库的方法已经发生变化，已经修复。
